[package]
name = "lyrics-follower"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cqt-rs = "0.1.0"
hound = "3.5"
image = "0.24"
imageproc = "0.23"
ndarray = "0.15"
